version: '3'

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: data-fast
      POSTGRES_USER: data-fast
      POSTGRES_PASSWORD: data-fast
      POSTGRES_NAME: data-fast
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: